wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1669237869.691406
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 13
      - 14
      - 16
      - 23
      4: 3.9.13
      5: 0.13.5
      8:
      - 3
      - 5
created_at:
  desc: null
  value: '2022-11-22T15:26:53'
fine_tuned_model:
  desc: null
  value: ada:ft-jasincase-2022-11-22-20-43-54
hyperparams:
  desc: null
  value:
    batch_size: 8
    learning_rate_multiplier: 0.2
    n_epochs: 4
    prompt_loss_weight: 0.01
id:
  desc: null
  value: ft-w48TG7qPDnu9Ibsuq60fATs3
model:
  desc: null
  value: ada
n_train:
  desc: null
  value: 5615
object:
  desc: null
  value: fine-tune
organization_id:
  desc: null
  value: org-fxJYI8WdQnGDT3Fdd4xfj9Hk
result_files:
  desc: null
  value:
    bytes: 166478
    created_at: 1669149835
    filename: compiled_results.csv
    id: file-EYgcjGFmPZmsHWfne40hVcj0
    object: file
    purpose: fine-tune-results
    status: processed
    status_details: null
status:
  desc: null
  value: succeeded
training_files:
  desc: null
  value:
    bytes: 2545982
    created_at: 1669148813
    filename: D:\data\metadating\train.jsonl
    id: file-sJ0tjfbGLFluRxNZMTB8z1bS
    object: file
    purpose: fine-tune
    status: processed
    status_details: null
updated_at:
  desc: null
  value: 1669149836
validation_files:
  desc: null
  value: []
