wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1669084209.830562
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 13
      - 14
      - 16
      - 23
      4: 3.9.13
      5: 0.13.5
      8:
      - 3
      - 5
created_at:
  desc: null
  value: '2022-11-21T21:12:36'
fine_tuned_model:
  desc: null
  value: ada:ft-jasincase-2022-11-22-02-29-15
hyperparams:
  desc: null
  value:
    batch_size: 8
    learning_rate_multiplier: 0.2
    n_epochs: 4
    prompt_loss_weight: 0.01
id:
  desc: null
  value: ft-OW0BlTRKUItf6mVuG2sdNsMz
model:
  desc: null
  value: ada
object:
  desc: null
  value: fine-tune
organization_id:
  desc: null
  value: org-fxJYI8WdQnGDT3Fdd4xfj9Hk
result_files:
  desc: null
  value:
    bytes: 166518
    created_at: 1669084156
    filename: compiled_results.csv
    id: file-bcqnmXE0OWNqjNCa4tAj4AP9
    object: file
    purpose: fine-tune-results
    status: processed
    status_details: null
status:
  desc: null
  value: succeeded
training_files:
  desc: null
  value:
    bytes: 2546078
    created_at: 1669083156
    filename: D:\data\metadating\train.jsonl
    id: file-6qWfTBCH7ycyVAC4uruqpZZY
    object: file
    purpose: fine-tune
    status: processed
    status_details: null
updated_at:
  desc: null
  value: 1669084156
validation_files:
  desc: null
  value: []
