wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.13
    start_time: 1669237860.522573
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 13
      - 14
      - 16
      - 23
      4: 3.9.13
      5: 0.13.5
      8:
      - 3
      - 5
created_at:
  desc: null
  value: '2022-11-21T21:33:49'
fine_tuned_model:
  desc: null
  value: curie:ft-jasincase-2022-11-22-03-03-23
hyperparams:
  desc: null
  value:
    batch_size: 8
    learning_rate_multiplier: 0.2
    n_epochs: 4
    prompt_loss_weight: 0.01
id:
  desc: null
  value: ft-LLQzim6un4n3Pnppmyjf5V81
model:
  desc: null
  value: curie
n_train:
  desc: null
  value: 5615
object:
  desc: null
  value: fine-tune
organization_id:
  desc: null
  value: org-fxJYI8WdQnGDT3Fdd4xfj9Hk
result_files:
  desc: null
  value:
    bytes: 166467
    created_at: 1669086204
    filename: compiled_results.csv
    id: file-MO6I2mtDIL32K9Ss8RabYQJX
    object: file
    purpose: fine-tune-results
    status: processed
    status_details: null
status:
  desc: null
  value: succeeded
training_files:
  desc: null
  value:
    bytes: 2546078
    created_at: 1669084429
    filename: D:\data\metadating\train.jsonl
    id: file-lQnqDByJi3s2KEXQdwSYSvur
    object: file
    purpose: fine-tune
    status: processed
    status_details: null
updated_at:
  desc: null
  value: 1669086204
validation_files:
  desc: null
  value: []
